NB_EPOCHS:
  value : 200
MODEL:
  value : "big"
LAYERS:
  value: "big"
DATASET:
  value : "small"
CONCAT:
  # "first", "last"
  value: []

LEARNING_RATE_EMB:
  value: 0.000005
LEARNING_RATE_GEN:
  value: 0.000005
LEARNING_RATE_DISC:
  value: 0.00005
TTUR:
  value : True
HALF:
  value : True
